# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev

matrix:
  include:

  - stage: "Test"
    name: "Check oldrelease"
    r: oldrel

  - stage: "Test"
    name: "Check release"
    r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("covr")'
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    after_failure:
    - find . -name testthat.Rout | xargs cat

  - stage: "Test"
    name: "Check devel"
    r: devel
